version: 1.0
app:
  instances:
    min: 1
    max: 2
  # configure endpoints
  endpoints: public
  version: 2e7a0178-77ee-42ee-9e73-a4a574215217
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
