version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 2e7a0178-77ee-42ee-9e73-a4a574215217
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
